# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-14 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HPhysics',
            new_name='Course',
        ),
    ]
