# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-14 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly', '0003_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
