# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly', '0004_delete_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
