# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-26 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly', '0006_auto_20170226_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_embed',
        ),
    ]
