# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-18 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='course',
        ),
    ]
