# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-18 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_test_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='course',
        ),
    ]
