# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-18 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_test_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(max_length=50)),
                ('q_1', models.CharField(max_length=1000)),
                ('ans_1', models.CharField(max_length=1000)),
                ('q_2', models.CharField(max_length=1000)),
                ('ans_2', models.CharField(max_length=1000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Course')),
            ],
        ),
    ]
