# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-19 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=50)),
                ('question_1', models.CharField(max_length=1000)),
                ('answer_1', models.CharField(max_length=1000)),
                ('question_2', models.CharField(max_length=1000)),
                ('answer_2', models.CharField(max_length=1000)),
            ],
        ),
    ]
