# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-19 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.DeleteModel(
            name='Tests',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
