# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_auto_20170319_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.CharField(max_length=1000)),
                ('answer_2', models.CharField(max_length=1000)),
                ('student_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='test',
            name='answer_2',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Test'),
        ),
    ]
