# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_auto_20170320_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_image',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
